### ISSUE TITLE
Still getting issue 

### ISSUE THREAD

**Issue by chWolfgang** [batstyx/Graveyard#26]
Greetings:
I am still getting this issue with the new HDT and  v1.23.0.3068.zip
--
Make sure you are using the latest version of the Plugin and HDT.

System.MissingMethodException: Method not found: 'System.String Hearthstone_Deck_Tracker.Utility.LocUtil.Get(System.String, Boolean)'.
   at HDT.Plugins.Graveyard.Strings.GetLocalized(String key)
   at HDT.Plugins.Graveyard.Plugin.OnLoad()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load() in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:line 93

--
I have removed Graveyard, restarted HDT, installed  a fresh Graveyard, restarted HDT and the error is there.
 
Thank you for your efforts with Graveyard - it is one of my favorites. Happy to answer questions and try different things if it would help.

**Comment by chWolfgang** [comment]
No error now. TYVM! (Not sure how or if I can mark this resolved.)
